#!/usr/bin/env python3
"""
plot_cache_perf.py
==================
Dedicated Standalone Visualization Generator for Cache Performance Benchmarks.

Reads structured benchmark JSON (or markdown fallback) generated by `cache_perf.py`
and generates publication-ready plots without requiring re-profiling via Linux `perf`.

Features:
- Unified 4-Stage Memory Hierarchy Plot (L1, L2, L3, DRAM)
  * Primary: Linear scale (linear-linear)
  * Optional: Log scale (log-log)
  * Layer-coded colors (L1: Purple, L2: Red, L3: Blue, DRAM: Black)
  * Engine-coded line styles (Linear Sweep: solid, Opt BFS: dashed, Unopt BFS: dash-dot, OOP: dotted)
- Simulation Throughput (MEval/sec) Plot with linear scaling
- Branch Misprediction Rate (%) Plot comparing branch predictability
- Edge-padded moving-average curve smoothing to isolate architectural trends from PMU jitter.
"""

import os
import sys
import json
import glob
import re
import argparse
from typing import Dict, Any, List, Tuple, Optional

# Ensure tests/ is in sys.path
_TESTS_DIR = os.path.dirname(os.path.abspath(__file__))
if _TESTS_DIR not in sys.path:
    sys.path.insert(0, _TESTS_DIR)

from pmu_harness import PmuStats


def smooth_curve(y, window_size: int = 15):
    """Moving average convolution with edge padding to avoid border distortion."""
    import numpy as np
    y_arr = np.asarray(y, dtype=float)
    if len(y_arr) < window_size or window_size <= 1:
        return y_arr
    box = np.ones(window_size) / window_size
    pad_left = window_size // 2
    pad_right = window_size - 1 - pad_left
    padded = np.pad(y_arr, (pad_left, pad_right), mode='edge')
    return np.convolve(padded, box, mode='valid')


def parse_numeric(s: str) -> float:
    """Parses suffixed metrics (e.g. 7.09B, 67.08K, 1.28M) into raw floats."""
    s = s.strip().replace(",", "").replace("%", "")
    if not s or s == "N/A":
        return 0.0
    mult = 1.0
    if s.endswith("B"):
        mult = 1e9
        s = s[:-1]
    elif s.endswith("M"):
        mult = 1e6
        s = s[:-1]
    elif s.endswith("K"):
        mult = 1e3
        s = s[:-1]
    try:
        return float(s) * mult
    except ValueError:
        return 0.0


def load_from_json(json_path: str) -> Tuple[Dict[str, Any], Dict[str, List[PmuStats]]]:
    """Loads benchmark metadata and PmuStats dictionaries from a JSON file."""
    with open(json_path, "r", encoding="utf-8") as f:
        doc = json.load(f)

    metadata = doc.get("metadata", {})
    raw_data = doc.get("data", {})
    
    data: Dict[str, List[PmuStats]] = {}
    for engine_key, stats_list in raw_data.items():
        data[engine_key] = [PmuStats.from_dict(item) for item in stats_list]

    return metadata, data


def parse_md_fallback(md_path: str) -> Tuple[Dict[str, Any], Dict[str, List[PmuStats]]]:
    """
    Fallback parser for existing legacy markdown benchmark reports.
    Extracts sizes, engines, PMU metrics, time, and evals.
    """
    with open(md_path, "r", encoding="utf-8") as f:
        content = f.read()

    metadata: Dict[str, Any] = {
        "mode": "chaotic",
        "cpu_model": "Unknown CPU",
        "pmu_events": "",
        "sizes": [],
        "engines": ["oop", "unopt", "opt", "sweep"],
        "source_file": md_path
    }

    m_mode = re.search(r"# Cache Fragmentation Profile \(([^)]+)\)", content)
    if m_mode:
        metadata["mode"] = m_mode.group(1).lower()

    m_cpu = re.search(r"CPU:\s*([^|]+)\|\s*PMU Events:\s*`([^`]+)`", content)
    if m_cpu:
        metadata["cpu_model"] = m_cpu.group(1).strip()
        metadata["pmu_events"] = m_cpu.group(2).strip()

    data: Dict[str, List[PmuStats]] = {
        "oop": [],
        "unopt": [],
        "opt": [],
        "sweep": []
    }

    engine_name_to_key = {
        "OOP": "oop",
        "Unopt BFS": "unopt",
        "Opt BFS": "opt",
        "Linear Sweep": "sweep",
        "Fragmented (OOP)": "oop",
        "Unoptimized (BFS)": "unopt",
        "Sorted (BFS)": "opt",
        "Linear (Sweep)": "sweep",
    }

    # Parse Table 1 (Overview table)
    # Expected columns: Size | Engine Variant | Instructions | Cycles | IPC | L1 Loads | L2 Loads | L3 Loads | DRAM Loads ...
    t1_match = re.search(r"## 1\. Hardware PMU & Cache Hierarchy Overview.*?\n\|(.*?)\n\|[-:| ]+\n(.*?)(?=\n##|\Z)", content, re.DOTALL)
    sizes_set = []
    
    if t1_match:
        rows = t1_match.group(2).strip().split("\n")
        for row in rows:
            cols = [c.strip() for c in row.strip("|").split("|")]
            if len(cols) < 9:
                continue
            try:
                size_val = int(cols[0].replace(",", ""))
            except ValueError:
                continue
            if size_val not in sizes_set:
                sizes_set.append(size_val)
            
            eng_str = cols[1]
            eng_key = engine_name_to_key.get(eng_str)
            if not eng_key:
                continue

            inst = parse_numeric(cols[2])
            cyc = parse_numeric(cols[3])
            l1_loads = parse_numeric(cols[5])
            l2_loads = parse_numeric(cols[6])
            l3_loads = parse_numeric(cols[7])
            dram_loads = parse_numeric(cols[8])
            brn = parse_numeric(cols[12]) if len(cols) > 12 else 0.0
            brn_miss = parse_numeric(cols[13]) if len(cols) > 13 else 0.0

            st = PmuStats(
                instructions=inst,
                cycles=cyc,
                l1_loads=l1_loads,
                l1_misses=l2_loads,
                l2_loads=l2_loads,
                l2_misses=l3_loads,
                l3_loads=l3_loads,
                dram_loads=dram_loads,
                branches=brn,
                branch_misses=brn_miss
            )
            data[eng_key].append(st)

    metadata["sizes"] = sorted(sizes_set)

    # Parse Table 7 (Execution Time & Throughput) for time_ms, evals, iterations
    t7_match = re.search(r"## 7\. Execution Time & Throughput.*?\n\|(.*?)\n\|[-:| ]+\n(.*?)(?=\n##|\Z)", content, re.DOTALL)
    if t7_match:
        rows = t7_match.group(2).strip().split("\n")
        for idx, row in enumerate(rows):
            cols = [c.strip() for c in row.strip("|").split("|")]
            if len(cols) < 13:
                continue
            try:
                size_val = int(cols[0].replace(",", ""))
            except ValueError:
                continue
            
            # Map: OOP (1,2,3), Unopt (4,5,6), Opt (7,8,9), Sweep (10,11,12)
            eng_col_map = [
                ("oop", 1, 2, 3),
                ("unopt", 4, 5, 6),
                ("opt", 7, 8, 9),
                ("sweep", 10, 11, 12)
            ]
            for eng_key, eval_col, time_col, meps_col in eng_col_map:
                if idx < len(data[eng_key]):
                    evals_per_iter = parse_numeric(cols[eval_col])
                    time_per_iter_ms = parse_numeric(cols[time_col])
                    
                    calib_time_ns = time_per_iter_ms * 1e6
                    iters = max(10, int(200_000_000 / calib_time_ns)) if calib_time_ns > 0 else max(10, int(20_000_000 / (size_val * 2)))
                    
                    st = data[eng_key][idx]
                    st.iterations = float(iters)
                    st.evals = float(evals_per_iter * iters)
                    st.time_ms = float(time_per_iter_ms * iters)

    return metadata, data


def find_latest_benchmark_file(directory: str = "tests/test_result/perf") -> Optional[str]:
    """Finds the most recent .json (or .md) benchmark file in the target directory."""
    json_files = glob.glob(os.path.join(directory, "cache_perf_*.json"))
    if json_files:
        return max(json_files, key=os.path.getmtime)
    md_files = glob.glob(os.path.join(directory, "cache_perf_*.md"))
    if md_files:
        return max(md_files, key=os.path.getmtime)
    return None


def plot_memory_hierarchy(
    metadata: Dict[str, Any],
    data: Dict[str, List[PmuStats]],
    scale: str = 'linear',
    smoothing: int = 15,
    output_path: Optional[str] = None,
    dpi: int = 300
) -> str:
    """
    Renders the 4-Stage Memory Hierarchy Decomposition across 4 subplots
    (L1, L2, L3, DRAM) using consistent engine colors and layer-specific Y-axes.
    """
    import matplotlib.pyplot as plt
    import matplotlib.ticker as ticker
    import numpy as np

    sizes = metadata.get("sizes", [])
    if not sizes and "oop" in data and len(data["oop"]) > 0:
        sizes = list(range(100, 100 + len(data["oop"]) * 100, 100))

    mode_name = metadata.get("mode", "Benchmark").upper()
    scale_title = "LINEAR" if scale == 'linear' else "LOG-LOG"

    fig, axes = plt.subplots(4, 1, figsize=(14, 16), sharex=True)
    fig.suptitle(
        f"Memory Hierarchy Decomposition: Loads per Iteration ({mode_name} — {scale_title})",
        fontsize=16, fontweight='bold', y=0.985
    )

    engine_styles = {
        'sweep': {'col': '#2E7D32', 'ls': '-', 'lw': 2.4, 'label': 'Linear Sweep'},   # Green
        'opt':   {'col': '#1565C0', 'ls': '-', 'lw': 2.4, 'label': 'Optimized BFS'},   # Blue
        'unopt': {'col': '#D32F2F', 'ls': '-', 'lw': 2.4, 'label': 'Unoptimized BFS'}, # Red
        'oop':   {'col': '#7B1FA2', 'ls': '-', 'lw': 2.4, 'label': 'Reactor OOP'},     # Purple
    }

    subplots_config = [
        (axes[0], 'Stage 1: L1 Data Cache (Loads)', 'l1_loads'),
        (axes[1], 'Stage 2: L2 Cache (L1 Misses)', 'l2_loads'),
        (axes[2], 'Stage 3: L3 Cache (L2 Misses)', 'l3_loads'),
        (axes[3], 'Stage 4: DRAM / Main Memory (Spill)', 'dram_loads')
    ]

    # Helper to calculate Loads per Iteration with smoothing
    def get_iter_norm(pass_name: str, attr: str):
        vals = []
        for i, s in enumerate(sizes):
            st = data[pass_name][i]
            # Use total iterations as denominator across the perf measurement window
            num_passes = 3 if s >= 100000 else 5
            total_iters = (st.iterations * num_passes) if st.iterations > 0 else 1.0
            val = getattr(st, attr, 0.0)
            vals.append(max(1e-7, val / total_iters))
        return smooth_curve(vals, window_size=smoothing)

    for ax, title, attr in subplots_config:
        ax.set_title(title, fontsize=13, fontweight='bold', pad=8)
        
        for eng_key in ['oop', 'unopt', 'opt', 'sweep']:
            cfg = engine_styles[eng_key]
            y_vals = get_iter_norm(eng_key, attr)
            ax.plot(sizes, y_vals, color=cfg['col'], linestyle=cfg['ls'], linewidth=cfg['lw'], label=cfg['label'])

        ax.set_xscale(scale)
        ax.set_yscale(scale)
        ax.set_ylabel('Loads per Iteration', fontsize=11, fontweight='bold')
        ax.grid(True, alpha=0.3, which='both' if scale == 'log' else 'major', linestyle='--')

        if scale == 'linear':
            ax.xaxis.set_major_formatter(ticker.FuncFormatter(lambda x, p: f"{int(x):,}"))
            def format_y(val, pos):
                if val >= 1e6: return f"{val/1e6:.1f}M" if (val % 1e6) != 0 else f"{int(val/1e6)}M"
                elif val >= 1e3: return f"{val/1e3:.1f}K" if (val % 1e3) != 0 else f"{int(val/1e3)}K"
                elif val >= 1: return f"{val:.1f}" if (val % 1) != 0 else f"{int(val)}"
                else: return f"{val:.2f}"
            ax.yaxis.set_major_formatter(ticker.FuncFormatter(format_y))

    # Set bottom subplot X-axis label
    axes[3].set_xlabel('Circuit Size (Gates)', fontsize=12, fontweight='bold')

    # Single unified legend at the bottom
    engine_handles = [
        plt.Line2D([0], [0], color=engine_styles['sweep']['col'], lw=engine_styles['sweep']['lw'], linestyle=engine_styles['sweep']['ls'], label=engine_styles['sweep']['label']),
        plt.Line2D([0], [0], color=engine_styles['opt']['col'], lw=engine_styles['opt']['lw'], linestyle=engine_styles['opt']['ls'], label=engine_styles['opt']['label']),
        plt.Line2D([0], [0], color=engine_styles['unopt']['col'], lw=engine_styles['unopt']['lw'], linestyle=engine_styles['unopt']['ls'], label=engine_styles['unopt']['label']),
        plt.Line2D([0], [0], color=engine_styles['oop']['col'], lw=engine_styles['oop']['lw'], linestyle=engine_styles['oop']['ls'], label=engine_styles['oop']['label'])
    ]

    fig.legend(
        handles=engine_handles, title="Engine Traversal",
        loc='lower center', bbox_to_anchor=(0.5, 0.008),
        ncol=4, frameon=True, fontsize=11, title_fontsize=12
    )

    plt.tight_layout(rect=[0, 0.035, 1, 0.975])

    if output_path:
        os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
        fig.savefig(output_path, bbox_inches='tight', dpi=dpi)
        print(f"[{scale_title}] 4-Subplot Memory Hierarchy plot saved to -> {output_path}")

    plt.close(fig)
    return output_path or ""


def plot_simulation_throughput(
    metadata: Dict[str, Any],
    data: Dict[str, List[PmuStats]],
    smoothing: int = 15,
    output_path: Optional[str] = None,
    dpi: int = 300
) -> str:
    """Renders the Simulation Throughput (MEval/sec) plot."""
    import matplotlib.pyplot as plt
    import matplotlib.ticker as ticker
    import numpy as np

    sizes = metadata.get("sizes", [])
    if not sizes and "oop" in data and len(data["oop"]) > 0:
        sizes = list(range(100, 100 + len(data["oop"]) * 100, 100))

    mode_name = metadata.get("mode", "Benchmark").upper()

    fig, ax = plt.subplots(figsize=(11, 6.8))
    ax.set_title(
        f"Simulation Throughput: Mega-Evaluations per Second ({mode_name})",
        fontsize=14, fontweight='bold', pad=15
    )

    def get_meps(pass_name: str):
        vals = []
        for i, s in enumerate(sizes):
            st = data[pass_name][i]
            time_s = st.time_ms / 1000.0 if st.time_ms > 0 else 1e-9
            vals.append((st.evals / time_s) / 1_000_000.0)
        return smooth_curve(vals, window_size=smoothing)

    # Continuous curves with consistent engine colors
    ax.plot(sizes, get_meps("sweep"), label="Linear Sweep", color="#2E7D32", linestyle='-', linewidth=2.5)
    ax.plot(sizes, get_meps("opt"), label="Optimized BFS", color="#1565C0", linestyle='-', linewidth=2.5)
    ax.plot(sizes, get_meps("unopt"), label="Unoptimized BFS", color="#D32F2F", linestyle='-', linewidth=2.5)
    ax.plot(sizes, get_meps("oop"), label="Reactor OOP", color="#7B1FA2", linestyle='-', linewidth=2.5)

    ax.set_xscale("linear")
    ax.xaxis.set_major_formatter(ticker.FuncFormatter(lambda x, p: f"{int(x):,}"))
    ax.set_xlabel("Circuit Size (Gates)", fontsize=12, fontweight='bold')
    ax.set_ylabel("Throughput (MEval / sec)", fontsize=12, fontweight='bold')
    ax.grid(True, alpha=0.3, linestyle='--')

    ax.legend(
        loc='upper center',
        bbox_to_anchor=(0.5, -0.14),
        ncol=4,
        frameon=True,
        fontsize=11
    )
    plt.tight_layout()

    if output_path:
        os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
        fig.savefig(output_path, bbox_inches='tight', dpi=dpi)
        print(f"Throughput plot saved to -> {output_path}")

    plt.close(fig)
    return output_path or ""


def plot_branch_misses(
    metadata: Dict[str, Any],
    data: Dict[str, List[PmuStats]],
    smoothing: int = 15,
    output_path: Optional[str] = None,
    dpi: int = 300
) -> str:
    """Renders the Branch Misprediction Rate (%) plot across circuit sizes."""
    import matplotlib.pyplot as plt
    import matplotlib.ticker as ticker

    sizes = metadata.get("sizes", [])
    if not sizes and "oop" in data and len(data["oop"]) > 0:
        sizes = list(range(100, 100 + len(data["oop"]) * 100, 100))

    mode_name = metadata.get("mode", "Benchmark").upper()

    fig, ax = plt.subplots(figsize=(11, 6.8))
    ax.set_title(
        f"Branch Misprediction Rate: Branch Miss % ({mode_name})",
        fontsize=14, fontweight='bold', pad=15
    )

    def get_miss_pct(pass_name: str):
        vals = []
        for i, s in enumerate(sizes):
            st = data[pass_name][i]
            branches = st.branches
            misses = st.branch_misses
            pct = (misses / branches * 100.0) if branches > 0 else 0.0
            vals.append(pct)
        return smooth_curve(vals, window_size=smoothing)

    # Continuous curves with consistent engine colors
    ax.plot(sizes, get_miss_pct("sweep"), label="Linear Sweep", color="#2E7D32", linestyle='-', linewidth=2.5)
    ax.plot(sizes, get_miss_pct("opt"), label="Optimized BFS", color="#1565C0", linestyle='-', linewidth=2.5)
    ax.plot(sizes, get_miss_pct("unopt"), label="Unoptimized BFS", color="#D32F2F", linestyle='-', linewidth=2.5)
    ax.plot(sizes, get_miss_pct("oop"), label="Reactor OOP", color="#7B1FA2", linestyle='-', linewidth=2.5)

    ax.set_xscale("linear")
    ax.xaxis.set_major_formatter(ticker.FuncFormatter(lambda x, p: f"{int(x):,}"))
    ax.yaxis.set_major_formatter(ticker.FuncFormatter(lambda y, p: f"{y:.1f}%"))
    ax.set_xlabel("Circuit Size (Gates)", fontsize=12, fontweight='bold')
    ax.set_ylabel("Branch Misprediction Rate (%)", fontsize=12, fontweight='bold')
    ax.grid(True, alpha=0.3, linestyle='--')

    ax.legend(
        loc='upper center',
        bbox_to_anchor=(0.5, -0.14),
        ncol=4,
        frameon=True,
        fontsize=11
    )
    plt.tight_layout()

    if output_path:
        os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
        fig.savefig(output_path, bbox_inches='tight', dpi=dpi)
        print(f"Branch misprediction plot saved to -> {output_path}")

    plt.close(fig)
    return output_path or ""


def main():
    parser = argparse.ArgumentParser(description="Standalone Plotter for Cache Performance Benchmark Data")
    parser.add_argument('--json', dest='json_path', type=str, default=None, help='Path to benchmark JSON data file')
    parser.add_argument('--md', dest='md_path', type=str, default=None, help='Path to legacy benchmark Markdown file')
    parser.add_argument('--scale', choices=['linear', 'log', 'both'], default='linear', help='Scale for memory hierarchy plot (default: linear)')
    parser.add_argument('--no-throughput', action='store_true', help='Skip throughput plot generation')
    parser.add_argument('--no-branch', action='store_true', help='Skip branch misprediction plot generation')
    parser.add_argument('--smoothing', type=int, default=15, help='Moving average smoothing window (default: 15, 1=raw)')
    parser.add_argument('--output-dir', type=str, default=None, help='Output directory for plots (default: same as input file)')
    parser.add_argument('--dpi', type=int, default=300, help='Plot resolution DPI (default: 300)')
    
    args = parser.parse_args()

    input_file = args.json_path or args.md_path
    if not input_file:
        input_file = find_latest_benchmark_file()
        if not input_file:
            print("Error: No benchmark data found in 'tests/test_result/perf'. Run 'python tests/cache_perf.py' first.")
            sys.exit(1)
        print(f"Auto-selected latest benchmark data: {input_file}")

    if input_file.endswith(".json"):
        metadata, data = load_from_json(input_file)
    elif input_file.endswith(".md"):
        print(f"Parsing legacy markdown file: {input_file}")
        metadata, data = parse_md_fallback(input_file)
    else:
        print(f"Error: Unsupported file format '{input_file}'. Expected .json or .md.")
        sys.exit(1)

    out_dir = args.output_dir or os.path.dirname(os.path.abspath(input_file))
    base_name = os.path.splitext(os.path.basename(input_file))[0]
    # Strip any trailing '_funnel' or '_throughput' if present
    base_name = re.sub(r"_(hierarchy_linear|hierarchy_log|throughput|funnel|branch_misses)$", "", base_name)

    print(f"\nGenerating plots for {metadata.get('mode', 'benchmark').upper()} (Sizes: {len(metadata.get('sizes', []))} points)...")

    # 1. Memory Hierarchy Plot(s)
    if args.scale in ['linear', 'both']:
        out_linear = os.path.join(out_dir, f"{base_name}_hierarchy_linear.png")
        plot_memory_hierarchy(metadata, data, scale='linear', smoothing=args.smoothing, output_path=out_linear, dpi=args.dpi)

    if args.scale in ['log', 'both']:
        out_log = os.path.join(out_dir, f"{base_name}_hierarchy_log.png")
        plot_memory_hierarchy(metadata, data, scale='log', smoothing=args.smoothing, output_path=out_log, dpi=args.dpi)

    # 2. Simulation Throughput Plot
    if not args.no_throughput:
        out_throughput = os.path.join(out_dir, f"{base_name}_throughput.png")
        plot_simulation_throughput(metadata, data, smoothing=args.smoothing, output_path=out_throughput, dpi=args.dpi)

    # 3. Branch Misprediction Rate Plot
    if not args.no_branch:
        out_branch = os.path.join(out_dir, f"{base_name}_branch_misses.png")
        plot_branch_misses(metadata, data, smoothing=args.smoothing, output_path=out_branch, dpi=args.dpi)

    print("All requested plots successfully generated.\n")


if __name__ == '__main__':
    main()
