/* Generated by Cython 3.2.9 */

#ifndef __PYX_HAVE__Const
#define __PYX_HAVE__Const

#include "Python.h"

#ifndef __PYX_HAVE_API__Const

#ifdef CYTHON_EXTERN_C
    #undef __PYX_EXTERN_C
    #define __PYX_EXTERN_C CYTHON_EXTERN_C
#elif defined(__PYX_EXTERN_C)
    #ifdef _MSC_VER
    #pragma message ("Please do not define the '__PYX_EXTERN_C' macro externally. Use 'CYTHON_EXTERN_C' instead.")
    #else
    #warning Please do not define the '__PYX_EXTERN_C' macro externally. Use 'CYTHON_EXTERN_C' instead.
    #endif
#else
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C Py_ssize_t __pyx_v_5Const_MODE;
__PYX_EXTERN_C int __pyx_v_5Const_DEBUG;
__PYX_EXTERN_C double __pyx_v_5Const_DELAY;
__PYX_EXTERN_C int __pyx_v_5Const_UI_MODE;

#endif /* !__PYX_HAVE_API__Const */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

/* WARNING: Use PyImport_AppendInittab("Const", PyInit_Const) instead of calling PyInit_Const directly from Python 3.5 */
PyMODINIT_FUNC PyInit_Const(void);

#if PY_VERSION_HEX >= 0x03050000 && (defined(__GNUC__) || defined(__clang__) || defined(_MSC_VER) || (defined(__cplusplus) && __cplusplus >= 201402L))
#if defined(__cplusplus) && __cplusplus >= 201402L
[[deprecated("Use PyImport_AppendInittab(\"Const\", PyInit_Const) instead of calling PyInit_Const directly.")]] inline
#elif defined(__GNUC__) || defined(__clang__)
__attribute__ ((__deprecated__("Use PyImport_AppendInittab(\"Const\", PyInit_Const) instead of calling PyInit_Const directly."), __unused__)) __inline__
#elif defined(_MSC_VER)
__declspec(deprecated("Use PyImport_AppendInittab(\"Const\", PyInit_Const) instead of calling PyInit_Const directly.")) __inline
#endif
static PyObject* __PYX_WARN_IF_PyInit_Const_INIT_CALLED(PyObject* res) {
  return res;
}
#define PyInit_Const() __PYX_WARN_IF_PyInit_Const_INIT_CALLED(PyInit_Const())
#endif

#endif /* !__PYX_HAVE__Const */
